# Generated by Django 2.2.5 on 2019-09-05 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='激活状态')),
                ('name', models.CharField(default='', max_length=32, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=256, verbose_name='密码')),
                ('mobile', models.CharField(default='', max_length=12, verbose_name='手机号')),
                ('email', models.EmailField(default='', max_length=128, verbose_name='邮箱地址')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
